gridmaps:
    image: "selcolumbia/osm-gridmaps:0.1"
    links:
      - "db:db"
    volumes:
      # note that application.yml is placed in tmp because it will be modified
      # by server/init.sh before being copied into osm config dir.
      # database.yml and nginx.conf are mounted directly because they're not
      # modified in container.
      - ./application.yml:/tmp/application.yml
      - ./database.yml:/home/app/openstreetmap-website/config/database.yml
      - ./gridmaps-nginx.conf:/etc/nginx/sites-enabled/gridmaps-nginx.conf

gridmaps-cgimap:
    image: "selcolumbia/osm-gridmaps-cgimap:0.2"
    links:
      - "db:db"
    volumes:
      - ./application.yml:/tmp/application.yml
      - ./database.yml:/home/app/openstreetmap-website/config/database.yml
      - ./gridmaps-nginx-cgimap.conf:/etc/nginx/sites-enabled/gridmaps-nginx-cgimap.conf
    ports:
      - "80:80"

db:
    image: "selcolumbia/osm-db:0.1"

dev:
    image: "selcolumbia/osm-gridmaps-dev:0.1"
    volumes:
      - ~/src/openstreetmap-website/:/src/openstreetmap-website
      - ./database.yml:/openstreetmap-website/config/database.yml
      - ./application.yml:/openstreetmap-website/config/application.yml
    links:
      - "db:db"
    ports:
      - "3000:3000"
