version: '2'

volumes:
  database:
    driver: local

services:
  web:
    image: "osm/web"
    depends_on:
      - db
    volumes:
      - ./application.yml:/tmp/application.yml
      - ./database.yml:/home/app/openstreetmap-website/config/database.yml
      - ./gridmaps-nginx.conf:/etc/nginx/sites-enabled/gridmaps-nginx.conf

  web-cgimap:
    image: "osm/web-cgimap"
    depends_on:
      - db
    volumes:
      - ./application.yml:/tmp/application.yml
      - ./database.yml:/home/app/openstreetmap-website/config/database.yml
      - ./gridmaps-nginx-cgimap.conf:/etc/nginx/sites-enabled/gridmaps-nginx-cgimap.conf
    ports:
      - "80:80"

  db:
    image: "osm/db"
    volumes:
      - database:/var/lib/postgresql/data

  dev:
    image: "osm/web-dev"
    volumes:
      - ~/src/openstreetmap-website/:/src/openstreetmap-website
      - ./database.yml:/openstreetmap-website/config/database.yml
      - ./application.yml:/openstreetmap-website/config/application.yml
    depends_on:
      - db
    ports:
      - "3000:3000"
