version: '2'

volumes:
  database:
    driver: local

services:
  #  web:
  #    image: "osm/web"
  #    depends_on:
  #      - db

  web-cgimap:
    image: "osm/web-cgimap"
    depends_on:
      - db
    ports:
      - "80:80"

  osmosis:
    image: "osmosis"
    depends_on:
      - db
    volumes:
      - ./import:/project/import

  db:
    image: "osm/db"
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
